name: cement_final
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.9.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - liblzma=5.8.2=hfd05255_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - packaging=26.0=pyhcf101f3_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h0159041_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - setuptools=80.10.1=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h6ed50ae_3
  - tornado=6.5.4=py311h3485c13_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wcwidth=0.4.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - zeromq=4.3.5=h5bddc39_9
  - pip:
      - annotated-types==0.7.0
      - ase==3.27.0
      - bibtexparser==1.4.3
      - blake3==1.0.8
      - boto3==1.42.35
      - botocore==1.42.35
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - chgnet==0.4.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.4
      - emmet-core==0.86.2
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - idna==3.11
      - jinja2==3.1.6
      - jmespath==1.1.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - latexcodec==3.0.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - monty==2025.3.3
      - mp-api==0.45.15
      - mpmath==1.3.0
      - msgpack==1.1.2
      - narwhals==2.15.0
      - networkx==3.6.1
      - numpy==2.4.1
      - nvidia-ml-py3==7.352.0
      - orjson==3.11.5
      - palettable==3.3.3
      - pandas==3.0.0
      - pillow==12.1.0
      - plotly==6.5.2
      - pybtex==0.25.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pymatgen==2025.10.7
      - pymatgen-io-validation==0.1.2
      - pyparsing==3.3.2
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - requests==2.32.5
      - ruamel-yaml==0.19.1
      - s3transfer==0.16.0
      - scipy==1.17.0
      - smart-open==7.5.0
      - spglib==2.7.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - torch==2.10.0
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uncertainties==3.2.3
      - urllib3==2.6.3
      - wrapt==2.0.1
prefix: C:\Users\ACER\anaconda3\envs\cement_final
